/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Executive;

import Business.EcoSystem;
import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.ContractorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Company.AnalyticsOrganization;
import Business.Organization.Company.ExecutiveOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shaohanghu
 */
public class CompExecutiveWorkArea extends javax.swing.JPanel {

    JPanel userProcessContainer;
    CompanyEnterprise enterprise;
    EcoSystem system;
    UserAccount account;
    ExecutiveOrganization org;
    Network network;
    
    
    
    public  CompExecutiveWorkArea(JPanel userProcessContainer,
            Enterprise enterprise, Network network, Organization organization,
            EcoSystem business, UserAccount account) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.enterprise = (CompanyEnterprise)enterprise;
            this.system = business;
            this.account = account;
            this.org = (ExecutiveOrganization) organization;
            this.network = network;
            addContractor();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        compExeWorkAreaPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonNewStation = new javax.swing.JButton();
        buttonContractor = new javax.swing.JButton();
        buttonMaintenance = new javax.swing.JButton();
        buttonMngFund = new javax.swing.JButton();
        buttonAnaNewStation = new javax.swing.JButton();
        buttonAnaMaintenance = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1150, 600));

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setDividerLocation(300);

        compExeWorkAreaPanel.setBackground(new java.awt.Color(255, 255, 255));
        compExeWorkAreaPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(compExeWorkAreaPanel);

        jPanel2.setBackground(new java.awt.Color(128, 172, 216));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Compnay Executive Work Area");

        buttonNewStation.setBackground(new java.awt.Color(255, 255, 255));
        buttonNewStation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonNewStation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/newStation.png"))); // NOI18N
        buttonNewStation.setText("New Station Building Request");
        buttonNewStation.setToolTipText("");
        buttonNewStation.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonNewStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewStationActionPerformed(evt);
            }
        });

        buttonContractor.setBackground(new java.awt.Color(255, 255, 255));
        buttonContractor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonContractor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/coCompany.png"))); // NOI18N
        buttonContractor.setText("View Contractors");
        buttonContractor.setToolTipText("");
        buttonContractor.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonContractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContractorActionPerformed(evt);
            }
        });

        buttonMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        buttonMaintenance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Maintain.png"))); // NOI18N
        buttonMaintenance.setText("Maintenance Request");
        buttonMaintenance.setToolTipText("");
        buttonMaintenance.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMaintenanceActionPerformed(evt);
            }
        });

        buttonMngFund.setBackground(new java.awt.Color(255, 255, 255));
        buttonMngFund.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonMngFund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/fundIcon.png"))); // NOI18N
        buttonMngFund.setText(" Manage Funds");
        buttonMngFund.setToolTipText("");
        buttonMngFund.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonMngFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMngFundActionPerformed(evt);
            }
        });

        buttonAnaNewStation.setBackground(new java.awt.Color(255, 255, 255));
        buttonAnaNewStation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAnaNewStation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/anaIcon.png"))); // NOI18N
        buttonAnaNewStation.setText("Analytics Building Reqs");
        buttonAnaNewStation.setToolTipText("");
        buttonAnaNewStation.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonAnaNewStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnaNewStationActionPerformed(evt);
            }
        });

        buttonAnaMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        buttonAnaMaintenance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAnaMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/anaIcon.png"))); // NOI18N
        buttonAnaMaintenance.setText("Analytics Maintenance Reqs");
        buttonAnaMaintenance.setToolTipText("");
        buttonAnaMaintenance.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonAnaMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnaMaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonContractor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonMngFund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonNewStation, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonAnaNewStation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAnaMaintenance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAnaNewStation, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAnaMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNewStation, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMngFund, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonContractor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewStationActionPerformed
        // TODO add your handling code here:
        compExeWorkAreaPanel.removeAll();
        ExeSubmittedBuildingReq panel = new ExeSubmittedBuildingReq(compExeWorkAreaPanel, enterprise, org);
        compExeWorkAreaPanel.add("ExeSubmittedBuildingReq", panel);
        CardLayout layout = (CardLayout) compExeWorkAreaPanel.getLayout();
        layout.next(compExeWorkAreaPanel);
        
    }//GEN-LAST:event_buttonNewStationActionPerformed

    private void buttonContractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContractorActionPerformed
        // TODO add your handling code here:
        compExeWorkAreaPanel.removeAll();
        ExeMngContractor panel = new ExeMngContractor(compExeWorkAreaPanel, enterprise);
        compExeWorkAreaPanel.add("ExeMngContractor", panel);
        CardLayout layout = (CardLayout) compExeWorkAreaPanel.getLayout();
        layout.next(compExeWorkAreaPanel);
    }//GEN-LAST:event_buttonContractorActionPerformed

    private void buttonMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMaintenanceActionPerformed
        // TODO add your handling code here:
        compExeWorkAreaPanel.removeAll();
        ExeSubmittedMaintenReq panel = new ExeSubmittedMaintenReq(compExeWorkAreaPanel, enterprise, org);
        compExeWorkAreaPanel.add("ExeSubmittedMaintenReq", panel);
        CardLayout layout = (CardLayout) compExeWorkAreaPanel.getLayout();
        layout.next(compExeWorkAreaPanel);
        
    }//GEN-LAST:event_buttonMaintenanceActionPerformed

    private void buttonMngFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMngFundActionPerformed
        // TODO add your handling code here:
        compExeWorkAreaPanel.removeAll();
        ExeMngFunds panel = new ExeMngFunds(compExeWorkAreaPanel, network, enterprise, account, org);
        compExeWorkAreaPanel.add("ExeMngFunds", panel);
        CardLayout layout = (CardLayout) compExeWorkAreaPanel.getLayout();
        layout.next(compExeWorkAreaPanel);
    }//GEN-LAST:event_buttonMngFundActionPerformed

    private void buttonAnaNewStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnaNewStationActionPerformed
        // TODO add your handling code here:
        compExeWorkAreaPanel.removeAll();
        ExeViewNewRequest panel = new ExeViewNewRequest(compExeWorkAreaPanel, network, enterprise, account, org);
        compExeWorkAreaPanel.add("ExeViewNewRequest", panel);
        CardLayout layout = (CardLayout) compExeWorkAreaPanel.getLayout();
        layout.next(compExeWorkAreaPanel);
    }//GEN-LAST:event_buttonAnaNewStationActionPerformed

    private void buttonAnaMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnaMaintenanceActionPerformed
        // TODO add your handling code here:
        compExeWorkAreaPanel.removeAll();
        ExeViewMaintenanceRequest panel = new ExeViewMaintenanceRequest(compExeWorkAreaPanel, network, enterprise, account, org);
        compExeWorkAreaPanel.add("ExeViewMaintenanceRequest", panel);
        CardLayout layout = (CardLayout) compExeWorkAreaPanel.getLayout();
        layout.next(compExeWorkAreaPanel);
    }//GEN-LAST:event_buttonAnaMaintenanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnaMaintenance;
    private javax.swing.JButton buttonAnaNewStation;
    private javax.swing.JButton buttonContractor;
    private javax.swing.JButton buttonMaintenance;
    private javax.swing.JButton buttonMngFund;
    private javax.swing.JButton buttonNewStation;
    private javax.swing.JPanel compExeWorkAreaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private void addContractor() {
        for(Enterprise enterp : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterp.getEnterpriseType().getValue().equals("Contractor") ){
                //enterp = (ContractorEnterprise) enterp;
                if(enterprise.getContractorList() == null){
                    System.out.println(
                            "no constructor list");
                }
                else{
                    enterprise.getContractorList().add((ContractorEnterprise) enterp);
                }
                
            }
        }
        
        
    }
}
