/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Executive;

import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.ContractorEnterprise;
import Business.Network.Network;
import Business.Organization.Company.ExecutiveOrganization;
import Business.Organization.Contractor.CoopContractor;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DriverMaintenanceRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaohanghu
 */
public class ExeMngContractor extends javax.swing.JPanel {

    /**
     * Creates new form ExeMngContractor
     */
    JPanel userProcessContainer;
    CompanyEnterprise enterprise;
    
    public  ExeMngContractor(JPanel compExeWorkAreaPanel, CompanyEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = compExeWorkAreaPanel;
        this.enterprise = enterprise;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 122, 164));
        jLabel1.setText("Avaliable Contractors");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 330, 46));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Contractor Name", "Price p/ Station", "Price p/ pile"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 690, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/cooperate1.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 50, 930, 550));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
          model.setRowCount(0);
          if(enterprise.getCoopContractorList()== null){
                System.out.println(
                      "list empty");    
           }
          else{
               for (CoopContractor r : enterprise.getCoopContractorList()) {
               Object row[] = new Object[3];
               row[0] = r.getName();
               row[1] = r.getStationPrice();
               row[2] = r.getPilePrice();
               model.addRow(row);
            }
          }
    }
}
