/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Executive;

import Business.Enterprise.CompanyEnterprise;
import Business.Organization.Company.ExecutiveOrganization;
import Business.WorkRequest.ExecutiveMaintenanceRequest;
import Business.WorkRequest.ExecutiveNewLocationRequest;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaohanghu
 */
public class ExeSubmittedMaintenReq extends javax.swing.JPanel {

    /**
     * Creates new form ExeSubmittedMaintenReq
     */
    JPanel userProcessContainer;
    CompanyEnterprise enterprise;
    ExecutiveOrganization org;
    
    public  ExeSubmittedMaintenReq(JPanel compExeWorkAreaPanel,
            CompanyEnterprise enterprise, ExecutiveOrganization org) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.enterprise = (CompanyEnterprise)enterprise;
         this.org = (ExecutiveOrganization) org;
         refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 122, 164));
        jLabel1.setText("Maintenance Request for Contractor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 573, 34));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Executive", "Contractor", "RepairMan", "Date", "Station", "Pile#", "Status"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(1).setPreferredWidth(50);
            table.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 799, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/cooperate3.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 740, 250));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            if(org.getExecutiveImplementationWorkQueue()== null){
                
            }
            else{
                for (ExecutiveMaintenanceRequest r : org.getExecutiveMaintenanceWorkQueue().getList()) {
               Object row[] = new Object[8];
               row[0] = r;
               row[1] = r.getSender();
               row[2] = r.getRecevingContractor();
               row[3] = r.getReceiver();
               row[4] = format.format(r.getRequestDate());
               row[5] = r.getRequestedStation();
               row[6] = r.getRequestedPile();
               row[7] = r.getStatus();
               model.addRow(row);
                }
           }
    }
}
