/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Executive;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Company.ExecutiveOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.AnalyticsMaintenanceRequest;
import Business.WorkRequest.AnalyticsNewStationRequest;
import Business.WorkRequest.ExecutiveMaintenanceRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shaohanghu
 */
public class ExeViewMaintenanceReq2 extends javax.swing.JPanel {

    /**
     * Creates new form ExeViewMaintenanceReq2
     */
    JPanel userProcessContainer;
    Network network;
    Enterprise enterprise;
    UserAccount account;
    ExecutiveOrganization org;
    AnalyticsMaintenanceRequest request;
    
    public ExeViewMaintenanceReq2(JPanel userProcessContainer,
            AnalyticsMaintenanceRequest o, UserAccount account,
            ExecutiveOrganization org, Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
//        this.network = network;
//        this.enterprise = enterprise;
        this.request = o;
        this.account = account;
        this.org = org;
        this.enterprise = enterprise;
         DisplayContent();
         comboStatus.removeAllItems();
         comboStatus.addItem("REJECTED");
         comboStatus.addItem("APPROVED");
         comboStatus.addItem("INVALID");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        txtLocation = new javax.swing.JTextField();
        buttonApprove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFromUser = new javax.swing.JTextField();
        buttonConfirmStatusChange = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox();
        labelReceiver = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Proceed To Executive:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 429, 180, -1));

        txtStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStatus.setEnabled(false);
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 206, 250, -1));

        txtReason.setColumns(20);
        txtReason.setRows(5);
        txtReason.setEnabled(false);
        jScrollPane1.setViewportView(txtReason);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 246, -1, 122));

        txtLocation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLocation.setEnabled(false);
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 148, 250, -1));

        buttonApprove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonApprove.setForeground(new java.awt.Color(102, 122, 164));
        buttonApprove.setText("Generate Work Order");
        buttonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApproveActionPerformed(evt);
            }
        });
        add(buttonApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 425, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Requested By:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 92, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Pile ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 179, 180, -1));

        txtFromUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtFromUser.setEnabled(false);
        add(txtFromUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 90, 250, -1));

        buttonConfirmStatusChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonConfirmStatusChange.setForeground(new java.awt.Color(102, 122, 164));
        buttonConfirmStatusChange.setText("Confirm");
        buttonConfirmStatusChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmStatusChangeActionPerformed(evt);
            }
        });
        add(buttonConfirmStatusChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 381, 98, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Error:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 246, 180, -1));

        txtPile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtPile.setEnabled(false);
        add(txtPile, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 177, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Requested Date:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 121, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Processing Executive:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 468, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Change Status To:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 388, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 122, 164));
        jLabel1.setText("Charging Station Maintenance Request from User");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 50));

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDate.setEnabled(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 119, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Request Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 208, 180, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 382, 210, 30));
        add(labelReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 468, 210, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Suggested Location:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 150, 180, -1));

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(102, 122, 164));
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/userFeedback.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 920, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApproveActionPerformed
        // TODO add your handling code here:
        if(!request.getStatus().equals("APPROVED")){
            JOptionPane.showMessageDialog(null, "Need Approval Before Proceed to Executive");
        }
        else{
            ExecutiveMaintenanceRequest geneReq = new ExecutiveMaintenanceRequest();
            geneReq.setRequestedPile(request.getRequestedPile());
            geneReq.setMessage(request.getMessage());
            geneReq.setSender(account);
            geneReq.setRequestedStation(request.getRequestedLocation());
            geneReq.setRequestedPile(request.getRequestedPile());

            ExeGeneMaintenanceReq panel = new ExeGeneMaintenanceReq(userProcessContainer, request, account, org, geneReq, enterprise);
            userProcessContainer.add("ExeGeneMaintenanceReqReq", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_buttonApproveActionPerformed

    private void buttonConfirmStatusChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmStatusChangeActionPerformed
        // TODO add your handling code here:
        request.setStatus(comboStatus.getSelectedItem().toString());
        request.setReceiver(account);
        request.setResolveDate(new Date());
        DisplayContent();
        JOptionPane.showMessageDialog(null, "Status Changed");
    }//GEN-LAST:event_buttonConfirmStatusChangeActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApprove;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonConfirmStatusChange;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReceiver;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFromUser;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPile;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void DisplayContent() {
        txtDate.setText(request.getRequestDate().toString());
        txtFromUser.setText(request.getSender().getUsername());
        txtLocation.setText(request.getRequestedLocation().getName());
        txtPile.setText(String.valueOf(request.getRequestedPile().getId()));
        txtStatus.setText(request.getStatus());
        txtReason.setText(request.getMessage());
        labelReceiver.setText(account.getUsername());
    }
}
