/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Executive;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Company.ExecutiveOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.AnalyticsNewStationRequest;
import Business.WorkRequest.DriverNewLocationRequest;
import Business.WorkRequest.ExecutiveNewLocationRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shaohanghu
 */
public class ExeViewNewRequest2 extends javax.swing.JPanel {

    /**
     * Creates new form ExeViewNewRequest2
     */
    JPanel userProcessContainer;
    Network network;
    Enterprise enterprise;
    UserAccount account;
    ExecutiveOrganization org;
    AnalyticsNewStationRequest request;
    
    public ExeViewNewRequest2(JPanel userProcessContainer, AnalyticsNewStationRequest o,
            UserAccount account, ExecutiveOrganization org,
            Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
//        this.network = network;
//        this.enterprise = enterprise;
        this.request = o;
        this.account = account;
        this.org = org;
        this.enterprise = enterprise;
         DisplayContent();
         comboStatus.removeAllItems();
         comboStatus.addItem("REJECTED");
         comboStatus.addItem("APPROVED");
         comboStatus.addItem("INVALID");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtFromUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        buttonApprove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        buttonConfirmStatusChange = new javax.swing.JButton();
        txtPile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelReceiver = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(102, 122, 164));
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 31));

        txtReason.setColumns(20);
        txtReason.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReason.setRows(5);
        txtReason.setEnabled(false);
        jScrollPane1.setViewportView(txtReason);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 262, 320, 122));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Requested By:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 90, 180, -1));

        txtFromUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtFromUser.setEnabled(false);
        add(txtFromUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 88, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Reason:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 262, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Requested Date:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 119, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Change Status To:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 398, 180, -1));

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDate.setEnabled(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 117, 250, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 392, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Suggested Location:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 177, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Proceed To Executive:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 439, 180, -1));

        txtLocation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLocation.setEnabled(false);
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 175, 250, -1));

        buttonApprove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonApprove.setForeground(new java.awt.Color(102, 122, 164));
        buttonApprove.setText("Generate Work Order");
        buttonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApproveActionPerformed(evt);
            }
        });
        add(buttonApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 435, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Suggested Pile#");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 206, 180, -1));

        buttonConfirmStatusChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonConfirmStatusChange.setForeground(new java.awt.Color(102, 122, 164));
        buttonConfirmStatusChange.setText("Confirm");
        buttonConfirmStatusChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmStatusChangeActionPerformed(evt);
            }
        });
        add(buttonConfirmStatusChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 391, 98, 30));

        txtPile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtPile.setEnabled(false);
        add(txtPile, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 204, 250, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Processing Executive:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 478, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 122, 164));
        jLabel1.setText("Building New Station Work Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 404, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Request Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 235, 180, -1));

        labelReceiver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(labelReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 478, 210, 25));

        txtStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStatus.setEnabled(false);
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 233, 250, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Address:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 148, 180, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtAddress.setEnabled(false);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 146, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/workRequest.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApproveActionPerformed
        // TODO add your handling code here:
        if(!request.getStatus().equals("APPROVED")){
            JOptionPane.showMessageDialog(null, "Need Approval Before Proceed");
        }
        else{
            ExecutiveNewLocationRequest geneReq = new ExecutiveNewLocationRequest();
            geneReq.setNumPiles(request.getNumPiles());
            geneReq.setMessage(request.getMessage());
            geneReq.setSender(account);
            geneReq.setFullAddress(request.getFullAddress());
            geneReq.setRequestedLocation(request.getRequestedLocation());

            ExeGeneBuildingReq panel = new ExeGeneBuildingReq(userProcessContainer, request, account, org, geneReq, enterprise);
            userProcessContainer.add("ExeGeneBuildingReq", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_buttonApproveActionPerformed

    private void buttonConfirmStatusChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmStatusChangeActionPerformed
        // TODO add your handling code here:
        request.setStatus(comboStatus.getSelectedItem().toString());
        request.setReceiver(account);
        request.setResolveDate(new Date());
        DisplayContent();
        JOptionPane.showMessageDialog(null, "Status Changed");
    }//GEN-LAST:event_buttonConfirmStatusChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApprove;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonConfirmStatusChange;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReceiver;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFromUser;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPile;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void DisplayContent() {
        txtDate.setText(request.getRequestDate().toString());
        txtFromUser.setText(request.getSender().getUsername());
        txtLocation.setText(request.getRequestedLocation().getX() + "," + request.getRequestedLocation().getY());
        txtAddress.setText(request.getFullAddress());
        txtPile.setText(String.valueOf(request.getNumPiles()));
        txtStatus.setText(request.getStatus());
        txtReason.setText(request.getMessage());
        labelReceiver.setText(account.getUsername());
    }
}
