/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Analytics;

import Business.Organization.Company.AnalyticsOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.AnalyticsNewStationRequest;
import Business.WorkRequest.DriverNewLocationRequest;
import Business.WorkRequest.ExecutiveNewLocationRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shaohanghu
 */
public class CompAnalyticsNewStationDetailJPanrl extends javax.swing.JPanel {

    /**
     * Creates new form CompAnalyticsNewStationDetailJPanrl
     */
    private JPanel userProcessContainer;
    DriverNewLocationRequest request;
    UserAccount account;
    AnalyticsOrganization org;
    
    public  CompAnalyticsNewStationDetailJPanrl(JPanel userProcessContainer,
            DriverNewLocationRequest o, UserAccount account,
            AnalyticsOrganization org) {
        
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.request = o;
         this.account = account;
         this.org = org;
         DisplayContent();
         comboStatus.removeAllItems();
         comboStatus.addItem("REJECTED");
         comboStatus.addItem("APPROVED");
         comboStatus.addItem("INVALID");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFromUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        buttonApprove = new javax.swing.JButton();
        buttonConfirmStatusChange = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labelReceiver = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        txtLocation1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 113, 162));
        jLabel1.setText("Build New Charging Station Request from User");
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 477, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Requested By:");
        jLabel3.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        txtFromUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtFromUser.setEnabled(false);
        add(txtFromUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Requested Date:");
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDate.setEnabled(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Coordinates:");
        jLabel5.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txtLocation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLocation.setEnabled(false);
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Suggested Pile#");
        jLabel6.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        txtPile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtPile.setEnabled(false);
        add(txtPile, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Request Status:");
        jLabel7.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txtStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStatus.setEnabled(false);
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 250, -1));

        txtReason.setColumns(20);
        txtReason.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReason.setRows(5);
        txtReason.setEnabled(false);
        jScrollPane1.setViewportView(txtReason);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 250, 122));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Reason:");
        jLabel8.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Change Status To:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 180, -1));

        comboStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 210, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Proceed To Executive:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 176, -1));

        buttonApprove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        buttonApprove.setForeground(new java.awt.Color(102, 122, 164));
        buttonApprove.setText("Generate Executive Ticket");
        buttonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApproveActionPerformed(evt);
            }
        });
        add(buttonApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 216, 28));

        buttonConfirmStatusChange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        buttonConfirmStatusChange.setForeground(new java.awt.Color(102, 122, 164));
        buttonConfirmStatusChange.setText("Confirm");
        buttonConfirmStatusChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmStatusChangeActionPerformed(evt);
            }
        });
        add(buttonConfirmStatusChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 98, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Processing Analytics:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 182, -1));

        labelReceiver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(labelReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 213, 25));

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(40, 113, 162));
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 31));

        txtLocation1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLocation1.setEnabled(false);
        add(txtLocation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Suggested Location:");
        jLabel12.setPreferredSize(new java.awt.Dimension(180, 16));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/requestBG.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmStatusChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmStatusChangeActionPerformed
        // TODO add your handling code here:
        request.setStatus(comboStatus.getSelectedItem().toString());
        request.setReceiver(account);
        request.setResolveDate(new Date());
        DisplayContent();
        JOptionPane.showMessageDialog(null, "Status Changed");
    }//GEN-LAST:event_buttonConfirmStatusChangeActionPerformed

    private void buttonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApproveActionPerformed
        // TODO add your handling code here:
        if(!request.getStatus().equals("APPROVED")){
            JOptionPane.showMessageDialog(null, "Need Approval Before Proceed to Executive");
        }
        else{
            AnalyticsNewStationRequest geneReq = new AnalyticsNewStationRequest();
            geneReq.setNumPiles(request.getNumPiles());
            geneReq.setMessage(request.getMessage());
            geneReq.setSender(account);
            geneReq.setFullAddress(request.getFullAddress());
            geneReq.setRequestedLocation(request.getRequestedLocation());


            CompAnalyticsGenerateExecutiveNewStationReqJPanel panel = new CompAnalyticsGenerateExecutiveNewStationReqJPanel(userProcessContainer, request, account, org, geneReq);
            userProcessContainer.add("generateNewStationReq", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_buttonApproveActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApprove;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonConfirmStatusChange;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReceiver;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFromUser;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtLocation1;
    private javax.swing.JTextField txtPile;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void DisplayContent() {
        txtFromUser.setText(request.getSender().getUsername());
        txtDate.setText(request.getRequestDate().toString());
        txtLocation.setText(request.getRequestedLocation().getX() + "," + request.getRequestedLocation().getY());
        txtLocation1.setText(request.getFullAddress());
        txtPile.setText(String.valueOf(request.getNumPiles()));
        txtStatus.setText(request.getStatus());
        txtReason.setText(request.getMessage());
        labelReceiver.setText(account.getUsername());
  
    }
}
