/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Analytics;

import Business.Organization.Company.AnalyticsOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.AnalyticsMaintenanceRequest;
import Business.WorkRequest.DriverMaintenanceRequest;
import Business.WorkRequest.ExecutiveMaintenanceRequest;
import Business.WorkRequest.ExecutiveNewLocationRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shaohanghu
 */
public class CompAnalyticsGenerateExecutiveMaintenanceReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompAnalyticsGenerateExecutiveMaintenanceReqJPanel
     */
    
    private JPanel userProcessContainer;
    AnalyticsMaintenanceRequest request;
    UserAccount account;
    AnalyticsOrganization org;
    
    public CompAnalyticsGenerateExecutiveMaintenanceReqJPanel(
            JPanel userProcessContainer, DriverMaintenanceRequest request,
            UserAccount account, AnalyticsOrganization org,
            AnalyticsMaintenanceRequest geneReq) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = geneReq;
        this.account = account;
        this.org = org;
        DisplayContent();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        txtStation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFromUser = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPile = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReason.setColumns(20);
        txtReason.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReason.setRows(5);
        jScrollPane1.setViewportView(txtReason);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 321, 223));

        txtStation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStation.setEnabled(false);
        add(txtStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Requested By:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        txtFromUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtFromUser.setEnabled(false);
        add(txtFromUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 30));

        confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(40, 113, 162));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 180, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Reason:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 97, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 113, 162));
        jLabel1.setText("Maintenance Request from Analytics");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 404, 50));

        txtPile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtPile.setEnabled(false);
        add(txtPile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 210, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Pile:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Station:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/analysisBG.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 890, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:

//        request.setRequestedLocation(location);
//        request.s(Integer.parseInt(txtPile.getText()));
        request.setMessage(txtReason.getText());
        request.setStatus("PENDING");
        org.getAnalyticsMaintenanceWorkQueue().add(request);

        JOptionPane.showMessageDialog(null, "Request Submitted!");
        userProcessContainer.remove(this);
    }//GEN-LAST:event_confirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFromUser;
    private javax.swing.JTextField txtPile;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtStation;
    // End of variables declaration//GEN-END:variables

    private void DisplayContent() {
        txtFromUser.setText(request.getSender().getUsername());
        txtStation.setText(request.getRequestedLocation().toString());
        txtPile.setText(request.getRequestedPile().toString());
         txtReason.setText("---From Origin User---\n" + request.getMessage() + "\n---End User Message--- \n" + "---From Analytics---\nType Here\n---End Analytics Message---");
    }
}
