/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Analytics;

import Business.Organization.Company.AnalyticsOrganization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.AnalyticsMaintenanceRequest;
import Business.WorkRequest.DriverMaintenanceRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaohanghu
 */
public class CompAnalyticsApprovedMaintenanceRequests extends javax.swing.JPanel {

    /**
     * Creates new form CompAnalyticsApprovedMaintenanceRequests
     */
    JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory;
    UserAccount account;
    AnalyticsOrganization org;
    
    public CompAnalyticsApprovedMaintenanceRequests(JPanel compAnalyticsWorkArea,
            OrganizationDirectory organizationDirectory, UserAccount account,
            AnalyticsOrganization org) {
        initComponents();
        this.userProcessContainer = compAnalyticsWorkArea;
        this.organizationDirectory = organizationDirectory;
        this.account = account;
        this.org = org;
        refreshTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "User", "Date", "Station", "Pile", "Status"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 60, 720, 260));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 113, 162));
        jLabel1.setText("Maintenance Requests for Executive");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 461, 46));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/executiveBG.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 556, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
       DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
             SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            if(org.getAnalyticsMaintenanceWorkQueue()== null){
                
            }
            else{
                for (AnalyticsMaintenanceRequest r : org.getAnalyticsMaintenanceWorkQueue().getList()) {
               Object row[] = new Object[6];
               row[0] = r;
               row[1] = r.getSender();
               row[2] = format.format(r.getRequestDate());
               row[5] = r.getStatus();
               row[3] = r.getRequestedLocation();
               row[4] = r.getRequestedPile();
               model.addRow(row);
           }
            }
           
    }
}
