/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Analytics;

import Business.Organization.Company.AnalyticsOrganization;
import Business.StationMap.Coordinate;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.AnalyticsNewStationRequest;
import Business.WorkRequest.DriverNewLocationRequest;
import Business.WorkRequest.ExecutiveNewLocationRequest;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userinterface.User.UserReportAShortageJPanel.geocoding;

/**
 *
 * @author shaohanghu
 */
public class CompAnalyticsGenerateExecutiveNewStationReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompAnalyticsGenerateExecutiveNewStationReqJPanel
     */
    private JPanel userProcessContainer;
    AnalyticsNewStationRequest request;
    UserAccount account;
    AnalyticsOrganization org;
    ExecutiveNewLocationRequest geneReq;
    
    public CompAnalyticsGenerateExecutiveNewStationReqJPanel(
            JPanel userProcessContainer, DriverNewLocationRequest request,
            UserAccount account, AnalyticsOrganization org,
            AnalyticsNewStationRequest geneReq) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = geneReq;
        this.account = account;
        this.org = org;
        DisplayContent();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtXcoor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        txtPile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtFromUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtYcoor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFullAdd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonGeneCoordinate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("X Coordinates:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));

        txtXcoor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtXcoor.setEnabled(false);
        add(txtXcoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Suggested Pile#:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, -1));

        confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(40, 113, 162));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 300, 40));

        txtPile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(txtPile, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 300, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 113, 162));
        jLabel1.setText("Build New Charging Station Request from Analytics");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 550, 50));

        txtReason.setColumns(20);
        txtReason.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtReason.setRows(5);
        jScrollPane1.setViewportView(txtReason);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 301, 209));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Requested By:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, -1));

        txtFromUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtFromUser.setEnabled(false);
        add(txtFromUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 300, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Reason:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 97, -1));

        txtYcoor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtYcoor.setEnabled(false);
        add(txtYcoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 300, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Y Coordinates:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        txtFullAdd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(txtFullAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 300, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Full Address:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));

        buttonGeneCoordinate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGeneCoordinate.setForeground(new java.awt.Color(40, 113, 162));
        buttonGeneCoordinate.setText("Generate Coordinate");
        buttonGeneCoordinate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGeneCoordinateActionPerformed(evt);
            }
        });
        add(buttonGeneCoordinate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 300, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/analysisBG.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
       Double x = Double.parseDouble(txtXcoor.getText());
       Double y = Double.parseDouble(txtYcoor.getText());
        Coordinate location = new Coordinate(x, y);
        request.setRequestedLocation(location);
        request.setFullAddress(txtFullAdd.getText());
        request.setNumPiles(Integer.parseInt(txtPile.getText()));
        request.setMessage(txtReason.getText());
        request.setStatus("PENDING");
        request.setFullAddress(txtFullAdd.getText());
        org.getAnalyticsNewStationWorkQueue().add(request);
        
        JOptionPane.showMessageDialog(null, "Request Submitted!");
        
        userProcessContainer.remove(this);
    }//GEN-LAST:event_confirmActionPerformed
    public boolean patternCorrect(String input){
        Pattern p = Pattern.compile("^[a-zA-Z0-9 ]+$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    private void buttonGeneCoordinateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGeneCoordinateActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String address= txtFullAdd.getText();
        boolean flag=patternCorrect(address);
        String [] parsed = address.split(" ");
        if (!flag){
            JOptionPane.showMessageDialog(null, "Address should follow the format", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (address.length()==0 || parsed.length==0){
            JOptionPane.showMessageDialog(null, "Address should not be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (parsed.length<2){
            JOptionPane.showMessageDialog(null, "There should be enough information to find the place", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        
        String url="https://maps.googleapis.com/maps/api/geocode/json?&address=";
        for (int i=0;i<parsed.length-1;i++){
            url+=parsed[i]+"+";
        }
        url+=parsed[parsed.length-1];
        url+="&key=AIzaSyB4LQVH_DbM4JE9gJU8nDe9rkYL6iS2qwU";
        System.out.println(url);
        try
        {
            Coordinate co;
            co=geocoding(url);
            String txtCoordinate = "Latitude: "+co.getX()+" Longtitude: "+co.getY();
            txtXcoor.setText(String.valueOf(co.getX()));
            txtYcoor.setText(String.valueOf(co.getY()));
            txtFullAdd.setText(co.getFullAddress());
        } catch (IOException ex)
        {
            JOptionPane.showMessageDialog(null, "There is no search result matched", "Error", JOptionPane.ERROR_MESSAGE);
            return;
//            Logger.getLogger(UserReportAShortageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "There is no search result matched", "Error", JOptionPane.ERROR_MESSAGE);
            return;
//            Logger.getLogger(UserReportAShortageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonGeneCoordinateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGeneCoordinate;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFromUser;
    private javax.swing.JTextField txtFullAdd;
    private javax.swing.JTextField txtPile;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtXcoor;
    private javax.swing.JTextField txtYcoor;
    // End of variables declaration//GEN-END:variables

     private void DisplayContent() {
        txtFromUser.setText(request.getSender().getUsername());
        txtXcoor.setText(String.valueOf(request.getRequestedLocation().getX()));
        txtYcoor.setText(String.valueOf(request.getRequestedLocation().getY()));
        txtPile.setText(String.valueOf(request.getNumPiles()));
        txtFullAdd.setText(request.getFullAddress());
//        txtReason.setText("--------From Origin User:" + request.getMessage() + "End---------");
        txtReason.setText("---From Origin User---\n" + request.getMessage() + "\n---End User Message--- \n" + "---From Analytics---\nType Here\n---End Analytics Message---");
  
    }
}
