/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Admin;

import Business.EcoSystem;
import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;


/**
 *
 * @author shaohanghu
 */



public class CompAdminWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    CompanyEnterprise comp;
    OrganizationDirectory orgDir;
    EcoSystem system;
    Network network;
    /**
     * Creates new form CompAdminWorkArea
     */
    public CompAdminWorkAreaJPanel(JPanel userProcessContainer,
            Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.comp = (CompanyEnterprise) enterprise;
        this.system = business;
        this.network = network;
        valueLabel.setText(enterprise.getName());
        labelNetwork.setText("Network: "+ comp.getNetwork().getName());

    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        compAdminWorkArea = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        valueLabel = new javax.swing.JLabel();
        buttonMngOrd = new javax.swing.JButton();
        buttonMngAccount = new javax.swing.JButton();
        buttonMngStation = new javax.swing.JButton();
        labelNetwork = new javax.swing.JLabel();

        jSplitPane1.setDividerLocation(300);

        compAdminWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        compAdminWorkArea.setForeground(new java.awt.Color(255, 255, 255));
        compAdminWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(compAdminWorkArea);

        jPanel2.setBackground(new java.awt.Color(128, 172, 216));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");

        buttonMngOrd.setBackground(new java.awt.Color(255, 255, 255));
        buttonMngOrd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonMngOrd.setForeground(new java.awt.Color(40, 113, 162));
        buttonMngOrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/organ.png"))); // NOI18N
        buttonMngOrd.setText("Manage Organization");
        buttonMngOrd.setToolTipText("");
        buttonMngOrd.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonMngOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMngOrdActionPerformed(evt);
            }
        });

        buttonMngAccount.setBackground(new java.awt.Color(255, 255, 255));
        buttonMngAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonMngAccount.setForeground(new java.awt.Color(40, 113, 162));
        buttonMngAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/useracc.png"))); // NOI18N
        buttonMngAccount.setText("Manage User Account");
        buttonMngAccount.setToolTipText("");
        buttonMngAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonMngAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMngAccountActionPerformed(evt);
            }
        });

        buttonMngStation.setBackground(new java.awt.Color(255, 255, 255));
        buttonMngStation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonMngStation.setForeground(new java.awt.Color(40, 113, 162));
        buttonMngStation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/newStation.png"))); // NOI18N
        buttonMngStation.setText("Manage Charging Stations");
        buttonMngStation.setToolTipText("");
        buttonMngStation.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonMngStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMngStationActionPerformed(evt);
            }
        });

        labelNetwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNetwork.setForeground(new java.awt.Color(255, 255, 255));
        labelNetwork.setText("<network>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(buttonMngOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonMngAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonMngStation, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(buttonMngOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buttonMngAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(buttonMngStation, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))

        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMngOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMngOrdActionPerformed
                compAdminWorkArea.removeAll();
                CompMngOrgJPanel panel = new CompMngOrgJPanel(compAdminWorkArea, comp.getOrganizationDirectory());
                compAdminWorkArea.add("CompMngOrgJPanel", panel);
                CardLayout layout = (CardLayout) compAdminWorkArea.getLayout();
                layout.next(compAdminWorkArea);
    }//GEN-LAST:event_buttonMngOrdActionPerformed

    private void buttonMngAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMngAccountActionPerformed
                 // TODO add your handling code here:
                 compAdminWorkArea.removeAll();
                CompCreateUserJPanel panel = new CompCreateUserJPanel(compAdminWorkArea, comp.getOrganizationDirectory());
                compAdminWorkArea.add("CompCreateUserJPanel", panel);
                CardLayout layout = (CardLayout) compAdminWorkArea.getLayout();
                layout.next(compAdminWorkArea);
    }//GEN-LAST:event_buttonMngAccountActionPerformed

    private void buttonMngStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMngStationActionPerformed
        // TODO add your handling code here:
                compAdminWorkArea.removeAll();
                CompMngStationJPanel panel = new CompMngStationJPanel(compAdminWorkArea, comp.getOrganizationDirectory(), system, comp);
                compAdminWorkArea.add("CompMngStationJPanel", panel);
                CardLayout layout = (CardLayout) compAdminWorkArea.getLayout();
                layout.next(compAdminWorkArea);
    }//GEN-LAST:event_buttonMngStationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMngAccount;
    private javax.swing.JButton buttonMngOrd;
    private javax.swing.JButton buttonMngStation;
    private javax.swing.JPanel compAdminWorkArea;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelNetwork;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
