/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Company.Tenderee;

import Business.EcoSystem;
import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.ContractorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Contractor.ContractorTedererOrganization;
import Business.Organization.Contractor.CoopContractor;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkRequest.AnalyticsNewStationRequest;
import Business.WorkRequest.ContractorTenderRequest;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaohanghu
 */
public class CompTendereeWorkArea extends javax.swing.JPanel {
  private JPanel userProcessContainer;
    private CompanyEnterprise enterprise;
    private UserAccount userAccount;
     private EcoSystem system;
     private Network network;
     private ContractorTedererOrganization org;
    /**
     * Creates new form CompTendereeWorkArea
     */
    public CompTendereeWorkArea(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
         this.userAccount = account;
        this.enterprise = (CompanyEnterprise)enterprise;
        this.network = network;
        this.system = system;
        populateTable();
    }
    
     public void populateTable(){
         DefaultTableModel model = (DefaultTableModel) table.getModel();
         SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            model.setRowCount(0);
           
        
       if(enterprise.getWorkQueue()== null){
                //ContractorImplementationWorkQueue queue = new ContractorImplementationWorkQueue();
            }
            else
            
                for (WorkRequest r : enterprise.getWorkQueue().getWorkRequestList()) {
                    if(r instanceof ContractorTenderRequest ){
                         Object row[] = new Object[6];
                         row[0] = (ContractorTenderRequest)r;
                         row[1] = ((ContractorTenderRequest)r).getSendingContractor();
                         row[2] = ((ContractorTenderRequest)r).getNewLocationPrice();
                         row[3] = ((ContractorTenderRequest)r).getPriceEachPile();
                         row[4] =  format.format(((ContractorTenderRequest)r).getRequestDate());
                         row[5] = ((ContractorTenderRequest)r).getStatus();
                         model.addRow(row);
                        System.out.println("not null");
             
                }
                    }
             
       
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonProcessTicket = new javax.swing.JButton();
        buttonProcessTicket1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 122, 164));
        jLabel1.setText("Company Tenderee Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 507, 42));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ticket ID", "Contractor", "Price p. Station", "Price p. Pile", "Date Submitted", "Status"
            }
        ));
        jScrollPane2.setViewportView(table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 750, 285));

        buttonProcessTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonProcessTicket.setForeground(new java.awt.Color(102, 122, 164));
        buttonProcessTicket.setText("Accept and add to List");
        buttonProcessTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessTicketActionPerformed(evt);
            }
        });
        add(buttonProcessTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 247, 39));

        buttonProcessTicket1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonProcessTicket1.setForeground(new java.awt.Color(102, 122, 164));
        buttonProcessTicket1.setText("Reject");
        buttonProcessTicket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessTicket1ActionPerformed(evt);
            }
        });
        add(buttonProcessTicket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 247, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/tender.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 620, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProcessTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessTicketActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ContractorTenderRequest o = (ContractorTenderRequest)table.getValueAt(row,0);
        if(o.getStatus().equals("PENDING")){
            o.setStatus("SUCCESS");
            CoopContractor c = new CoopContractor(o.getSendingContractor(), o.getNewLocationPrice(),
            o.getPriceEachPile(), o.getSendingContractor().getName());
            enterprise.getCoopContractorList().add(c);
            JOptionPane.showMessageDialog(null, "Success!");
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "This ticket has closed! Cannot modify!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_buttonProcessTicketActionPerformed

    private void buttonProcessTicket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessTicket1ActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ContractorTenderRequest o = (ContractorTenderRequest)table.getValueAt(row,0);
        if(o.getStatus().equals("PENDING")){
             int n = JOptionPane.showConfirmDialog(null, "Reject the tender from " + o.getSendingContractor().getName() + " ?", "Reject?", JOptionPane.YES_NO_OPTION);
             if(n == 0){
                o.setStatus("REJECTED");
                JOptionPane.showMessageDialog(null, "Tender has been Rejected!");
             }
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "This ticket has closed! Cannot modify!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonProcessTicket1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProcessTicket;
    private javax.swing.JButton buttonProcessTicket1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
