/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Contractor.ImplementorRole;
import userinterface.Contractor.AdminRole.*;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.ExecutiveNewLocationRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
/**
 *
 * @author jindou
 */
public class ViewImplementDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewImplementDetailJPanel
     */
    JPanel userProcessContainer;
    ExecutiveNewLocationRequest request;
    public ViewImplementDetailJPanel(JPanel userProcessContainer,ExecutiveNewLocationRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        displayDetails(request);
    }
     private void displayDetails(ExecutiveNewLocationRequest request){
       
        String userAccount = request.getReceiver().getUsername();
        txtUA.setText(userAccount);
        
        Date date = request.getRequestDate();
        txtDate.setText(String.valueOf(date));
        
        String location = request.getFullAddress();
        txtLation.setText(location);
        
        int pileNum = request.getNumPiles();
        txtPileNum.setText(String.valueOf(pileNum));
        
        String name = request.getStationName();
        txtName.setText(name);
        
         String message = request.getMessage();
        txtInstruction.setText(message);
        txtInstruction.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUA = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtLation = new javax.swing.JTextField();
        lblName5 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        txtPileNum = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName7 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        lblName8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInstruction = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 248, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUA.setEditable(false);
        add(txtUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 116, 222, 30));

        lblName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName3.setText("Worker UserAccount");
        add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 118, -1, -1));

        lblName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName4.setText("Issue Date");
        add(lblName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 188, -1, -1));

        txtDate.setEditable(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 186, 222, 30));

        txtLation.setEditable(false);
        add(txtLation, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 252, 222, 30));

        lblName5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName5.setText("Station Location ");
        add(lblName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 254, -1, -1));

        lblName6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName6.setText("Pile Number");
        add(lblName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 319, -1, -1));

        txtPileNum.setEditable(false);
        add(txtPileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 317, 222, 30));

        txtName.setEditable(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 381, 224, 30));

        lblName7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName7.setText("Station Name");
        add(lblName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 383, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        enterpriseLabel.setText("View Assignment Details");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 23, 299, 30));

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 23, 101, 30));

        lblName8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName8.setText("Instructions");
        add(lblName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 437, -1, -1));

        txtInstruction.setColumns(20);
        txtInstruction.setRows(5);
        jScrollPane1.setViewportView(txtInstruction);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 437, 224, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/details.png"))); // NOI18N
        jLabel1.setText(" ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 1040, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtInstruction;
    private javax.swing.JTextField txtLation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPileNum;
    private javax.swing.JTextField txtUA;
    // End of variables declaration//GEN-END:variables
}
