/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Contractor.MaintainenceRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.CandidateRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author jindou
 */
public class EditProfileJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
     UserAccount account;
     EcoSystem system;
       private boolean isUserUnique;
    /**
     * Creates new form EditProfileJPanel
     */
    public EditProfileJPanel(JPanel userProcessContainer,UserAccount account,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
         displayResume(account);
    }
     private void displayResume(UserAccount account){
        String name = account.getName();
        txtName.setText(name);
        
        String userName = account.getUsername();
        txtUsername.setText(userName);
     
        String password = account.getPassword();
        txtpw.setText(password);
        
        txtReEnter.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtReEnter = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        rePWlbl = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblName6 = new javax.swing.JLabel();
        txtpw = new javax.swing.JTextField();
        pwlbl = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        txtName.setEditable(false);
        txtName.setText(" ");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 229, 36));

        txtReEnter.setEditable(false);
        add(txtReEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 229, 36));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/back.png"))); // NOI18N
        btnBack.setText(" ");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 50));

        rePWlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rePWlbl.setText("Re-enter ");
        add(rePWlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        txtUsername.setEditable(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 229, 36));

        lblName6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName6.setText("Username");
        add(lblName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        txtpw.setEditable(false);
        add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 229, 36));

        pwlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pwlbl.setText("Password");
        add(pwlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 110, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 120, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Edit Login Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 230, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MaintainenceWorkAreaJPanel mwajp = (MaintainenceWorkAreaJPanel) component;
        mwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtName.setEditable(false);
        txtUsername.setEditable(true);
        txtpw.setEditable(true);
        txtReEnter.setEditable(true);

        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
          
           
            String username = txtUsername.getText();
            String pw = txtpw.getText();
            
            Pattern password = Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{4,}$");
            Matcher pm = password.matcher(txtpw.getText());
            isUserUnique = userUnique(username);
        if(!pm.matches()){
            pwlbl.setForeground(Color.red);
            txtpw.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Password should be at least 4 digits, One letter one number.", "Warning",JOptionPane.WARNING_MESSAGE);
             pwlbl.setForeground(Color.BLACK);
            txtpw.setBorder(new JTextField().getBorder());
        }
        else if(!txtpw.getText().equals(txtReEnter.getText())){
            rePWlbl.setForeground(Color.red);
            txtReEnter.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Two password does not match", "Warning",JOptionPane.WARNING_MESSAGE);
            rePWlbl.setForeground(Color.BLACK);
            txtReEnter.setBorder(new JTextField().getBorder());
        }
       else if(isUserUnique == true){
          account.setUsername(username);
          account.setPassword(pw);
           btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);

            JOptionPane.showMessageDialog(null, " Profile successfully updated!");

          }else if (isUserUnique == false) {
              JOptionPane.showMessageDialog(null, "Username has already exist, please change to another one");
          }

              

                   

                
            
   

    }//GEN-LAST:event_btnSaveActionPerformed

     public Boolean userUnique(String username){
         
          for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    if (ua.getUsername().equalsIgnoreCase(txtUsername.getText())) {
                        return false;
                    }
                }
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.getUsername().equalsIgnoreCase(txtUsername.getText())) {
                            return false;
                        }
                    }
                }
            }
          }
          return true;
        
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel pwlbl;
    private javax.swing.JLabel rePWlbl;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReEnter;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtpw;
    // End of variables declaration//GEN-END:variables
}
