/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Contractor.AdminRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Company.ExecutiveOrganization;
import Business.Organization.Contractor.ContractorAdminOrganization;
import Business.Organization.Contractor.ImplementorOrganization;
import Business.Organization.Contractor.MaintenanceOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.WorkRequest;
import Business.WorkRequest.ContractorImplementRequest;
import Business.WorkRequest.ContractorRepairRequest;
import Business.WorkRequest.ContractorTenderRequest;
import Business.WorkRequest.ExecutiveMaintenanceRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author shaohanghu
 */
public class MaintenanceRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompExecutiveWorkArea
     */
    private JPanel userProcessContainer;
     private Enterprise enterprise;
     OrganizationDirectory organizationDirectory;
     List<ExecutiveMaintenanceRequest> maintenanceReqList;
     UserAccount account;
     private ContractorAdminOrganization org;
     //ExecutiveOrganization organization;
     private Network network;
     
     
    public MaintenanceRequestJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory,
             List<ExecutiveMaintenanceRequest> maintenanceReqList,
             UserAccount account,
           ContractorAdminOrganization organization,Enterprise enterprise,Network network) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        this.maintenanceReqList = maintenanceReqList;
        this.account = account;
          this.org = organization;
        this.enterprise = enterprise;
         this.network = network;
        //populateTable();
        refreshTable();
        populateRepairManCombo();
    }

      public void  populateRepairManCombo(){
        
          repairComboBox.removeAllItems();
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList() ){
               if(organization.getType() == Organization.Type.ContractorMaintenance){
                   for(UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList()){
                        if(userAccount.getIsWorking().booleanValue() == false)
                           repairComboBox.addItem(userAccount);
                       }
                        
                         
                     }
              }
        }

      private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
         SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            model.setRowCount(0);
           if(maintenanceReqList == null){
                System.out.println(
                      "list empty");
                
           }
            else{
                for (ExecutiveMaintenanceRequest r : maintenanceReqList) {
                    if(r.getRecevingContractor() == enterprise){
                        Object row[] = new Object[7]; 
                        row[0] = r;
                        row[1] = r.getSendingCompany();
                        row[2] = r.getReceiver();
                        row[3] = format.format(r.getRequestDate());
                        row[4] = r.getRequestedStation();
                        row[5] = r.getRequestedPile();
                        row[6] = r.getStatus();
                        model.addRow(row);
                    }
              
                }
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repairComboBox = new javax.swing.JComboBox();
        assignJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDetail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 233, 233));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        repairComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairComboBoxActionPerformed(evt);
            }
        });
        add(repairComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 250, -1));

        assignJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        assignJButton.setForeground(new java.awt.Color(40, 113, 162));
        assignJButton.setText("Assign");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        enterpriseLabel.setText("Assign Works to Repair Man");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 330, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request Type", "Exe Company", "Repair Man", "Date", "Station", "Pile#", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 750, 170));

        refreshJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(40, 113, 162));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 65, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/newStation1.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 170, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 113, 162));
        jLabel3.setText("Repair Man");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        btnDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(40, 113, 162));
        btnDetail.setText("View Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        add(btnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/repair.png"))); // NOI18N
        jLabel1.setText(" ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void repairComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairComboBoxActionPerformed
        // TODO add your handling code here:
       // populateTable();
    }//GEN-LAST:event_repairComboBoxActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        int selectedRow = table.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)table.getValueAt(selectedRow, 0); 
       
        request.setReceiver((UserAccount)repairComboBox.getSelectedItem());
        request.setStatus("SENT");
        UserAccount mainAccount = (UserAccount)repairComboBox.getSelectedItem();
        mainAccount.setIsWorking(true);
        
       // populateTable();
       refreshTable();
       populateRepairManCombo();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        refreshTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        ExecutiveMaintenanceRequest request = (ExecutiveMaintenanceRequest)table.getValueAt(selectedRow, 0);
         if(request.getReceiver() == null){
            JOptionPane.showMessageDialog(null, "Please assign an Repair Man first!!!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterpirse));
        userProcessContainer.add("ViewMaintainDetailJPanel", new ViewMaintainDetailJPanel(userProcessContainer, request));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnDetail;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JComboBox repairComboBox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
