/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Contractor.AdminRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.WorkRequest.CandidateRequest;
import Business.WorkRequest.FeedbackWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ResultCandidateRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    CandidateRequest request;
    Enterprise enterprise;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ResultCandidateRequestJPanel(JPanel userProcessContainer, CandidateRequest request, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.enterprise = enterprise;
        txtResult.setText("---OFFER---\nTYPE HERE\n---User Account: \nYour name plus your contact\n---Password:\nYour name plus your contact\n"
                + "Please change your username as\nUSERNAME: OrganizationName_First letter of your LastName+FirstName\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(40, 113, 162));
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 270, 130));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Result");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/candidateRequest.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 670, 560));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/back.png"))); // NOI18N
        btnBack.setText(" ");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Interview Result");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        request.setFeedback(txtResult.getText());
        request.setStatus("Completed");
         JOptionPane.showMessageDialog(null, "The result has been successfully sent to the candidate!");
        txtResult.setText("---OFFER---\nTYPE HERE\n---User Account: \nYour name plus your contact\n---Password:\nYour name plus your contact\n"
                + "Please change your username as\nUSERNAME: OrganizationName_First letter of your LastName+FirstName\n");
       
        String username = request.getName()+ request.getContact();
        String pw = username;
        System.out.println(username +" "+ pw);
        for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o.getType() == request.getOrgType()){
                o.getUserAccountDirectory().createUserAccount(username, pw,request.getName(), request.getDesiredRole());
            }
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCandidateRequestJPanel mcrjp = (ManageCandidateRequestJPanel) component;
        mcrjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
