/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Contractor.AdminRole;

import Business.Network.Network;
import Business.Organization.Organization;
import Business.WorkRequest.CandidateRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author jindou
 */
public class ViewDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailJPanel
     */
     JPanel userProcessContainer;
    CandidateRequest request;
    public ViewDetailJPanel(JPanel userProcessContainer, CandidateRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        displayResume(request);
    }
    
    private void displayResume(CandidateRequest request){
        String name = request.getName();
        txtName.setText(name);
        
        String contact = request.getContact();
        txtContact.setText(contact);
        
        Network area = request.getNetwork();
        String areaName = area.toString();
        txtArea.setText(areaName);
        
        Organization.Type position = request.getOrgType();
        String org = position.getValue();
        txtPosition.setText(org);
        
        String introduction = request.getMessage();
        txtIntroduction.setText(introduction);
        txtIntroduction.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        IntroductionJPane = new javax.swing.JScrollPane();
        txtIntroduction = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("View Person Profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 270, 60));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 119, -1, -1));

        txtName.setEditable(false);
        txtName.setText(" ");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 119, 229, 36));

        txtContact.setEditable(false);
        txtContact.setText(" ");
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 187, 229, 36));

        txtArea.setEditable(false);
        txtArea.setText(" ");
        add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 255, 229, 36));

        txtPosition.setEditable(false);
        txtPosition.setText(" ");
        add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 328, 229, 36));

        lblName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName2.setText("Contact");
        add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 187, -1, -1));

        lblName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName3.setText("Desired Working Area");
        add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 255, -1, -1));

        lblName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName4.setText("Desired Position");
        add(lblName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 328, -1, -1));

        lblName5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName5.setText("Brief Introduction");
        add(lblName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 400, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/back.png"))); // NOI18N
        btnBack.setText(" ");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 50));

        txtIntroduction.setColumns(20);
        txtIntroduction.setRows(5);
        IntroductionJPane.setViewportView(txtIntroduction);

        add(IntroductionJPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 350, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/candidateRequest.png"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 620, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCandidateRequestJPanel mcrjp = (ManageCandidateRequestJPanel) component;
        mcrjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane IntroductionJPane;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextArea txtIntroduction;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosition;
    // End of variables declaration//GEN-END:variables
}
