/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Candidate;

import java.awt.CardLayout;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CandidateOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FeedbackWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkRequest.CandidateRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jindou
 */
public class JobSearchStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JobSearchStatusJPanel
     */
     private JPanel userProcessContainer;
    private CandidateOrganization organization;
    //private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    
    public JobSearchStatusJPanel(JPanel userProcessContainer, UserAccount account, CandidateOrganization organization,EcoSystem system/* Enterprise enterprise*/) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        //this.enterprise = enterprise;
        this.system = system;
        this.userAccount = account;
       
        populateRequestTable();
    }

     public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = ((CandidateRequest) request).getEnterprise();
            row[2] = request.getStatus();
            String result = ((CandidateRequest) request).getFeedback();
            row[3] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requesJButton = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RequestType", "Company", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 710, 180));

        requesJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        requesJButton.setForeground(new java.awt.Color(40, 113, 162));
        requesJButton.setText("Send Resume");
        requesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesJButtonActionPerformed(evt);
            }
        });
        add(requesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 139, 33));

        btnDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(40, 113, 162));
        btnDetail.setText("View Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        add(btnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 140, 30));

        refreshJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(40, 113, 162));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 97, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/RESUME.png"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setPreferredSize(new java.awt.Dimension(1150, 600));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1150, 640));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("My Job Search Status");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 270, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void requesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterpirse));
        userProcessContainer.add("ResumeRequestJPanel", new ResumeRequestJPanel(userProcessContainer, userAccount, system));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requesJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        CandidateRequest request = (CandidateRequest)workRequestJTable.getValueAt(selectedRow, 0);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterpirse));
        userProcessContainer.add("ViewResultDetailJPanel", new ViewResultDetailJPanel(userProcessContainer, request));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton requesJButton;
    private javax.swing.JLabel title;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
