/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Candidate;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CandidateOrganization;
import Business.Organization.Contractor.ContractorAdminOrganization;
import Business.Organization.Organization;
import Business.Role.Contractor.ImplementorRole;
import Business.Role.Contractor.MaintenanceRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.CandidateRequest;
import Business.WorkRequest.FeedbackWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Contractor.AdminRole.ManageCandidateRequestJPanel;

/**
 *
 * @author raunak
 */
public class ResumeRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
     private EcoSystem system;
   
    /**
     * Creates new form RequestLabTestJPanel
     */
    public ResumeRequestJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system/*Enterprise enterprise*/) {
        initComponents();
        
       this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = system;
         txtName.setText(userAccount.getName());
        txtContact.setEditable(true);
         populateAreaComboBox();
         
         //populateOrgComboBox(enterprise);
       
    }
    
    public void populateAreaComboBox(){
        areaJComboBox.removeAllItems();
       for(Network network : system.getNetworkList() ){
            areaJComboBox.addItem(network);
        }
    }

     public void populateCompanyComboBox(Network network){
         companyComboBox.removeAllItems();
         for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise.getEnterpriseType().getValue().equals("Company")||enterprise.getEnterpriseType().getValue().equals("Contractor"))
                 companyComboBox.addItem(enterprise);
            
         }
     }
     
     
   public void populateOrgComboBox(Enterprise enterprise){
       orgComboBox.removeAllItems();
    
       Enterprise.EnterpriseType type = enterprise.getEnterpriseType();
       
        if(null!=type )switch (type) {
             case ContractorEnterprise:{
                 orgComboBox.addItem(Organization.Type.ContractorImplementor);
                 orgComboBox.addItem(Organization.Type.ContractorMaintenance);
                 break;
             }
              case CompanyEnterprise:{
                orgComboBox.addItem(Organization.Type.CompanyAnalytics);
                orgComboBox.addItem(Organization.Type.CompanyExecutive);
                orgComboBox.addItem(Organization.Type.CompanyTenderer);
                break;
              }
               default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        namelbl4 = new javax.swing.JLabel();
        namelbl5 = new javax.swing.JLabel();
        areaJComboBox = new javax.swing.JComboBox();
        companyComboBox = new javax.swing.JComboBox();
        namelbl8 = new javax.swing.JLabel();
        orgComboBox = new javax.swing.JComboBox();
        namelbl6 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        namelbl7 = new javax.swing.JLabel();
        namelbl9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIntroduction = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 230, 230));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(40, 113, 162));
        btnSubmit.setText("Submit ");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 110, 40));

        namelbl4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        namelbl4.setText("Contact");
        add(namelbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 88, 34));

        namelbl5.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        namelbl5.setText("Introduction:");
        add(namelbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 150, 34));

        areaJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        areaJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaJComboBoxActionPerformed(evt);
            }
        });
        add(areaJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 270, 34));

        companyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        companyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyComboBoxActionPerformed(evt);
            }
        });
        add(companyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 270, 34));

        namelbl8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        namelbl8.setText("Company");
        add(namelbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 81, 34));

        orgComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgComboBoxActionPerformed(evt);
            }
        });
        add(orgComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 270, 34));

        namelbl6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        namelbl6.setText("Organization");
        add(namelbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 128, 34));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText(" Candidate Information");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 300, 43));

        txtName.setEditable(false);
        txtName.setText(" ");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 270, 30));

        txtContact.setEditable(false);
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 270, 30));

        namelbl7.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        namelbl7.setText("Full Name");
        add(namelbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 34));

        namelbl9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        namelbl9.setText("Area");
        add(namelbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 88, 34));

        txtIntroduction.setColumns(20);
        txtIntroduction.setRows(5);
        jScrollPane1.setViewportView(txtIntroduction);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 270, 170));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(40, 113, 162));
        btnBack.setText("< Back");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/resumeBG.jpg"))); // NOI18N
        jLabel2.setText(" ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 970, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String introduction = txtIntroduction.getText();
        Network network = (Network) areaJComboBox.getSelectedItem();
        //Organization.Type type = (Organization.Type) orgComboBox.getSelectedItem();
        
        CandidateRequest request = new CandidateRequest();
        request.setMessage(introduction);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setContact(txtContact.getText());
        request.setName(userAccount.getName());
        request.setNetwork(network);
        request.setEnterprise((Enterprise)companyComboBox.getSelectedItem());
        request.setOrgType((Organization.Type)orgComboBox.getSelectedItem());
        if((Organization.Type)orgComboBox.getSelectedItem() == Organization.Type.ContractorImplementor){
            request.setDesiredRole(new ImplementorRole());
        }else if((Organization.Type)orgComboBox.getSelectedItem() == Organization.Type.ContractorMaintenance){
             request.setDesiredRole(new MaintenanceRole());
        }
        
        
        
       
        Enterprise companyName = (Enterprise)companyComboBox.getSelectedItem();
       
       Organization org = null;
         for (Organization organization : companyName.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CandidateOrganization){
                
                org = organization;
                break;
            }
        }
        if(org != null){
             companyName.getWorkQueue().getWorkRequestList().add(request);
             userAccount.getWorkQueue().getWorkRequestList().add(request);
               JOptionPane.showMessageDialog(null, "Your Resume has been successfull sent!");
               txtContact.setText("");
               txtName.setText("");
               txtIntroduction.setText("");
   }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void areaJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaJComboBoxActionPerformed
        Network network = (Network) areaJComboBox.getSelectedItem();
        if (network != null){
            populateCompanyComboBox(network);
        }
    }//GEN-LAST:event_areaJComboBoxActionPerformed

    private void companyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise)companyComboBox.getSelectedItem();
        if(enterprise != null){
            populateOrgComboBox(enterprise);
        }
    }//GEN-LAST:event_companyComboBoxActionPerformed

    private void orgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_orgComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        JobSearchStatusJPanel jssjp = (JobSearchStatusJPanel) component;
        jssjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areaJComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox companyComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namelbl4;
    private javax.swing.JLabel namelbl5;
    private javax.swing.JLabel namelbl6;
    private javax.swing.JLabel namelbl7;
    private javax.swing.JLabel namelbl8;
    private javax.swing.JLabel namelbl9;
    private javax.swing.JComboBox orgComboBox;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextArea txtIntroduction;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
