/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Candidate;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.ContractorEnterprise;
import Business.Enterprise.EVDriver;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.CandidateRole;
import Business.Role.EVDriverRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkRequest.CandidateRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
/**
 *
 * @author jindou
 */
public class UserRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserRegisterHPanel
     */
     private EcoSystem system;
     private JPanel userProcessContainer;
     //private boolean contactValid;
     private boolean isUserUnique;
     
    public UserRegisterJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
       populateAreaComboBox();
       populateUserTypeComboBox();
       
    }
   
     public void populateAreaComboBox(){
        areaJComboBox.removeAllItems();
        for(Network network : system.getNetworkList() ){
            areaJComboBox.addItem(network);
        }
    }

     public void populateUserTypeComboBox(){
         userTypeComboBox.removeAllItems();
         for(Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()){
            if(type == Enterprise.EnterpriseType.Candidate)
                 userTypeComboBox.addItem(type);
            
         }
     }
     
     
    
       
      /*Enterprise.EnterpriseType type = (Enterprise.EnterpriseType)typeComboBox.getSelectedItem();
       if(type == Enterprise.EnterpriseType.CompanyEnterprise){
           orgComboBox.addItem(Organization.Type.CompanyAnalytics);
           orgComboBox.addItem(Organization.Type.CompanyExecutive);
           orgComboBox.addItem(Organization.Type.CompanyTenderer);
       }else if(type == Enterprise.EnterpriseType.ContractorEnterprise){
           orgComboBox.addItem(Organization.Type.ContractorImplementor);
           orgComboBox.addItem(Organization.Type.ContractorMaintenance);
       }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        namelbl4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        areaJComboBox = new javax.swing.JComboBox();
        btnRegister = new javax.swing.JButton();
        userTypeComboBox = new javax.swing.JComboBox();
        namelbl8 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pwlbl = new javax.swing.JLabel();
        userNameSuccessLabel = new javax.swing.JLabel();
        rePWlbl = new javax.swing.JLabel();
        txtReEnter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(173, 204, 204));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("New Candidate Registration");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 390, 43));

        namelbl4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelbl4.setText("Area");
        add(namelbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 50, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 192, 33));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 192, 33));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 192, 33));

        areaJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        areaJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaJComboBoxActionPerformed(evt);
            }
        });
        add(areaJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 192, 34));

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 190, 40));

        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeComboBoxActionPerformed(evt);
            }
        });
        add(userTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 192, 34));

        namelbl8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelbl8.setText("User Type");
        add(namelbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, 34));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("Full Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, 33));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername.setText("Username");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 170, 34));

        pwlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pwlbl.setText("Password");
        add(pwlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 180, 34));

        userNameSuccessLabel.setText(" ");
        add(userNameSuccessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 50, 50));

        rePWlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rePWlbl.setText("Re-enter Password");
        add(rePWlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 180, 34));

        txtReEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReEnterActionPerformed(evt);
            }
        });
        add(txtReEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 192, 33));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/cooperate.png"))); // NOI18N
        jLabel1.setText(" ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 920, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void areaJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaJComboBoxActionPerformed
        //Network network = (Network) areaJComboBox.getSelectedItem();
       // if (network != null){
         //   populateCompanyComboBox(network);
      //  }
    }//GEN-LAST:event_areaJComboBoxActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
      
        Network network = (Network)areaJComboBox.getSelectedItem();
        String username = txtUsername.getText();
        String pw = txtPassword.getText();
        String name = txtName.getText();
        Pattern password = Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{4,}$");
        Matcher pm = password.matcher(txtPassword.getText());
        isUserUnique = userUnique(username);
        
        if (network == null) {
            areaJComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            areaJComboBox.setForeground(Color.red);

        }
        if (txtName.getText().isEmpty()) {
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtName.setForeground(Color.red);
            lblName.setForeground(Color.RED);
            

        }
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtUsername.setForeground(Color.red);

        }
        if (txtPassword.getText().isEmpty()) {
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtPassword.setForeground(Color.red);

        }
        if(txtReEnter.getText().isEmpty()) {
           txtReEnter .setBorder(BorderFactory.createLineBorder(Color.RED));
           txtReEnter.setForeground(Color.red);

        }
        if (userTypeComboBox == null) {
            userTypeComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            userTypeComboBox.setForeground(Color.red);

        }
        if (txtUsername.getText().isEmpty()
                || txtPassword.getText().isEmpty()
                || txtReEnter.getText().isEmpty()
                || txtName.getText().isEmpty()
                || userTypeComboBox == null) {
                
            JOptionPane.showMessageDialog(null, "Please Enter all fields", "Message",JOptionPane.INFORMATION_MESSAGE);
            
            lblName.setForeground(Color.BLACK);
            txtName.setBorder(new JTextField().getBorder());
            txtName.setForeground(Color.BLACK);
            txtUsername.setBorder(new JTextField().getBorder());
            txtUsername.setForeground(Color.BLACK);
             txtPassword.setBorder(new JTextField().getBorder());
            txtPassword.setForeground(Color.BLACK);
             txtReEnter .setBorder(new JTextField().getBorder());
           txtReEnter.setForeground(Color.BLACK);
           

            
        }else if(!pm.matches()){
            pwlbl.setForeground(Color.red);
            txtPassword.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Password should be at least 4 digits, One letter one number.", "Warning",JOptionPane.WARNING_MESSAGE);
              txtPassword.setForeground(Color.BLACK);
            txtPassword.setBorder(new JTextField().getBorder());
        }
        else if(!txtPassword.getText().equals(txtReEnter.getText())){
            rePWlbl.setForeground(Color.red);
            txtReEnter.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Two password does not match", "Warning",JOptionPane.WARNING_MESSAGE);
             txtReEnter.setForeground(Color.BLACK);
            txtReEnter.setBorder(new JTextField().getBorder());
        }
       else if(isUserUnique == true){
           Enterprise candidateEnterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, Enterprise.EnterpriseType.Candidate);
           Organization candidateOrganization = candidateEnterprise.getOrganizationDirectory().createOrganization(Organization.Type.Candidate,name);
           candidateOrganization.getUserAccountDirectory().createUserAccount(username, pw, name,new CandidateRole());
        
           JOptionPane.showMessageDialog(null, "You have been registered succesfully!");
           txtName.setText("");
           txtUsername.setText("");
           txtPassword.setText("");
           txtReEnter.setText("");
          }else if (isUserUnique == false) {
            lblUsername.setForeground(Color.red);
            txtUsername.setForeground(Color.RED);
            txtUsername.setBorder(new LineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Username has already exist, please change to another one","Message",JOptionPane.INFORMATION_MESSAGE);
            lblUsername.setForeground(Color.black);
            txtUsername.setForeground(Color.BLACK);
            txtUsername.setBorder(new JTextField().getBorder());
          }
       
    }//GEN-LAST:event_btnRegisterActionPerformed

     /*private void userNameKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
        txtUsername.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtUsername.setForeground(Color.BLACK);
    }
     
     private void uPassKeyTyped(java.awt.event.KeyEvent evt) {                               
        // TODO add your handling code here:
        txtPassword.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtPassword.setForeground(Color.BLACK);
    }*/
     
     public Boolean contactValidity(String candidateContact) {
        String regex = "\\(\\d{3}\\)-\\d{3}-\\d{4}";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(candidateContact);
        if(matcher.matches()){
            return true;
        }
        return false;
    }
     
      public Boolean userUnique(String username){
         
          for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    if (ua.getUsername().equalsIgnoreCase(txtUsername.getText())) {
                        return false;
                    }
                }
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.getUsername().equalsIgnoreCase(txtUsername.getText())) {
                            return false;
                        }
                    }
                }
            }
          }
          return true;
        
     }
     
    private void userTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTypeComboBoxActionPerformed

    private void txtReEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReEnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areaJComboBox;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel namelbl4;
    private javax.swing.JLabel namelbl8;
    private javax.swing.JLabel pwlbl;
    private javax.swing.JLabel rePWlbl;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtReEnter;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel userNameSuccessLabel;
    private javax.swing.JComboBox userTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
