/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserInvestorRegister;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.User.DriverRegisterJPanel;

/**
 *
 * @author adam
 */
public class UserInvestorWorkAreaJPanel extends javax.swing.JPanel
{

    JPanel userProcessContainer;
    EcoSystem system;

    public UserInvestorWorkAreaJPanel (JPanel userProcessContainer, EcoSystem system)
    {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        btnEVDriver = new javax.swing.JButton();
        btnInvestor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resgisterWorkArea = new javax.swing.JPanel();

        jSplitPane2.setDividerLocation(300);

        jPanel3.setBackground(new java.awt.Color(128, 172, 216));

        btnEVDriver.setBackground(new java.awt.Color(255, 255, 255));
        btnEVDriver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEVDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/EVicon.png"))); // NOI18N
        btnEVDriver.setText("Register as EVDriver");
        btnEVDriver.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEVDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEVDriverActionPerformed(evt);
            }
        });

        btnInvestor.setBackground(new java.awt.Color(255, 255, 255));
        btnInvestor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInvestor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/investorIcon.png"))); // NOI18N
        btnInvestor.setText("Register as Investor");
        btnInvestor.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEVDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(btnInvestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEVDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel3);

        resgisterWorkArea.setBackground(new java.awt.Color(255, 255, 255));
        resgisterWorkArea.setPreferredSize(new java.awt.Dimension(1150, 600));
        resgisterWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(resgisterWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEVDriverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEVDriverActionPerformed
    {//GEN-HEADEREND:event_btnEVDriverActionPerformed
        // TODO add your handling code here:
        DriverRegisterJPanel panel = new DriverRegisterJPanel(resgisterWorkArea,system);
        resgisterWorkArea.add("DriverRegisterJPanel", panel);
        CardLayout layout = (CardLayout) resgisterWorkArea.getLayout();
        layout.next(resgisterWorkArea);
    }//GEN-LAST:event_btnEVDriverActionPerformed

    private void btnInvestorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInvestorActionPerformed
    {//GEN-HEADEREND:event_btnInvestorActionPerformed
        // TODO add your handling code here:
        InvestorRegisterJPanel panel = new InvestorRegisterJPanel(resgisterWorkArea,system);
        resgisterWorkArea.add("InvestorRegisterJPanel", panel);
        CardLayout layout = (CardLayout) resgisterWorkArea.getLayout();
        layout.next(resgisterWorkArea);
    }//GEN-LAST:event_btnInvestorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEVDriver;
    private javax.swing.JButton btnInvestor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel resgisterWorkArea;
    // End of variables declaration//GEN-END:variables
}
