/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Investor;

import Business.EcoSystem;
import Business.Organization.InvestorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InverstmentWorkQueue;
import Business.WorkRequest.InvestmentRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adam
 */
public class InvestWorkAreaJPanel extends javax.swing.JPanel
{

     JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Organization organization;

    public InvestWorkAreaJPanel (JPanel userProcessContainer, EcoSystem system, UserAccount account, Organization organization)
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account=account;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        workarea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setDividerLocation(300);

        jPanel1.setBackground(new java.awt.Color(128, 172, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSend.setBackground(new java.awt.Color(255, 255, 255));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(40, 113, 162));
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/investIcon.png"))); // NOI18N
        btnSend.setText("Send Your Invest Request");
        btnSend.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 50));

        btnStart.setBackground(new java.awt.Color(255, 255, 255));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(40, 113, 162));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/investorIcon.png"))); // NOI18N
        btnStart.setText("        Start Investing");
        btnStart.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, 50));

        jSplitPane1.setLeftComponent(jPanel1);

        workarea.setBackground(new java.awt.Color(255, 255, 255));
        workarea.setPreferredSize(new java.awt.Dimension(1150, 600));
        workarea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSendActionPerformed
    {//GEN-HEADEREND:event_btnSendActionPerformed
        // TODO add your handling code here:
        InvestRequestJPanel panel = new InvestRequestJPanel(workarea,system,account,organization);
        workarea.add("InvestRequestJPanel", panel);
        CardLayout layout = (CardLayout) workarea.getLayout();
        layout.next(workarea);
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartActionPerformed
    {//GEN-HEADEREND:event_btnStartActionPerformed
        // TODO add your handling code here:
        boolean flag=false;
        InvestorOrganization io = (InvestorOrganization)organization;
        InverstmentWorkQueue workqueue = io.getInverstmentWorkQueue();
        for (int i=0;i<workqueue.getList().size();i++){
            InvestmentRequest ir = workqueue.getList().get(i);
            if (ir.getSender()==account){
                if (ir.getStatus().equals("APPROVED")){
                    flag=true;
                    
                }
            }
        }
        if (flag==false){
            JOptionPane.showMessageDialog(null, "You are not approved yet!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        StartInvestingJPanel panel = new StartInvestingJPanel(workarea,system,account,organization);
        workarea.add("StartInvestingJPanel", panel);
        CardLayout layout = (CardLayout) workarea.getLayout();
        layout.next(workarea);
    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workarea;
    // End of variables declaration//GEN-END:variables
}
