/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Investor;

import Business.EcoSystem;
import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InvestorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.InvestmentRequest;
import com.db4o.config.IdSystemConfiguration;
import java.awt.CardLayout;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adam
 */
public class sendInvestorRequestJPanel extends javax.swing.JPanel
{

    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Organization organization;
    int marketValue;
    public sendInvestorRequestJPanel (JPanel userProcessContainer, EcoSystem system, UserAccount account, Organization organization)
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account=account;
        this.organization=organization;
        for (Network net : system.getNetworkList()){
            for (Enterprise e : net.getEnterpriseDirectory().getEnterpriseList()){
                if (e.getEnterpriseType()==Enterprise.EnterpriseType.CompanyEnterprise){
                    CompanyEnterprise ce =(CompanyEnterprise)e;
                    marketValue=ce.getMarketValue();
                }
            }
        }
        LabelMarketValue.setText(String.valueOf(marketValue));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LabelMarketValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelEstimatedPercentage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Enter Your Invest Amount");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Amount you want to invest:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });
        add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 140, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Confirm>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Market Value of the company:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        LabelMarketValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMarketValue.setText(" ");
        add(LabelMarketValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Your estimated percentage:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        labelEstimatedPercentage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEstimatedPercentage.setText(" ");
        add(labelEstimatedPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 140, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Press Enter to show the percentage");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/investAmount.png"))); // NOI18N
        jLabel6.setText(" ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 260, 330, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNumActionPerformed
    {//GEN-HEADEREND:event_txtNumActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(txtNum.getText());
        System.out.println(num);
        double estimateShare = (double)((double)num/(double)marketValue)*100;
        if (estimateShare>50){
            JOptionPane.showMessageDialog(null, "You cannot invest more than 50%", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        estimateShare = (double)Math.round(estimateShare*100)/100;
        System.out.println(estimateShare);
        labelEstimatedPercentage.setText(String.valueOf(estimateShare)+"%");
        
    }//GEN-LAST:event_txtNumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InvestorOrganization io = (InvestorOrganization)organization;
        InvestmentRequest iwr = new InvestmentRequest();
        iwr.setSender(account);
        iwr.setRequestDate(new Date());
        iwr.setStatus("Pending");
        boolean flag=digitalCorrect(txtNum.getText());
        if (flag && txtNum.getText().length()>2){
            System.out.println("Investment request Sent");
            iwr.setAmount(Integer.parseInt(txtNum.getText()));
            io.getInverstmentWorkQueue().add(iwr);
            InvestSuccessJPanel panel = new InvestSuccessJPanel(userProcessContainer,system,account,organization);
            userProcessContainer.add("RequestLabTestJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else{
           JOptionPane.showMessageDialog(null, "You should enter the amount of invest", "Warning", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public  boolean digitalCorrect(String input){
        Pattern p = Pattern.compile("^[0-9]+(.[0-9]{2})?$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMarketValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelEstimatedPercentage;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
