/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.User;

import Business.EcoSystem;
import Business.Organization.EVDriverOrganization;
import Business.StationMap.ChargingPile;
import Business.StationMap.ChargingStation;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DriverMaintenanceRequest;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adam
 */
public class ReviewReportPileListJPanel extends javax.swing.JPanel
{
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    List<DriverMaintenanceRequest> requestList;
    
    /**
     * Creates new form ReviewReportPileListJPanel
     */


    ReviewReportPileListJPanel (JPanel userProcessContainer, EcoSystem system, UserAccount account,List<DriverMaintenanceRequest> requestList)
    {
        initComponents();
       this.userProcessContainer=userProcessContainer;
       this.system=system;        
       this.account=account;
       this.requestList=requestList;
       populateTable();
    }


        private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) pileTable.getModel();

        model.setRowCount(0);

        for (DriverMaintenanceRequest r : requestList) {
            
                Object row[] = new Object[4];
                row[0] = r.getRequestedPile();
                row[1] = r.getRequestedLocation();
                row[2]=  r.getMessage();
                model.addRow(row);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pileTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 210, 40));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setText("Submit>");
        btnSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 200, 40));

        pileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Pile Id", "Station", "Broken Detail"
            }
        ));
        jScrollPane1.setViewportView(pileTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 640, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Review Of Your Broken Pile List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/reviewBG.png"))); // NOI18N
        jLabel2.setText(" ");

        jLabel2.setPreferredSize(new java.awt.Dimension(1150, 600));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1070, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSubmitActionPerformed
    {//GEN-HEADEREND:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        EVDriverOrganization evo = (EVDriverOrganization) ReviewShortageRequestJPanel.findOrganization(account.getUsername(), account.getPassword(), system);
        for (DriverMaintenanceRequest r : requestList){
            
            evo.getDriverMaintenanceWorkQueue().add(r);
           // for(DriverMaintenanceRequest request : evo.getDriverMaintenanceWorkQueue().getList()){
             //   System.out.println(request.getReason());
         //   }
            
        }
        SubmitRequestSuccessJPanel panel = new SubmitRequestSuccessJPanel(userProcessContainer,system,account);
        userProcessContainer.add("SubmitRequestSuccessJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pileTable;
    // End of variables declaration//GEN-END:variables
}
