/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.User;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EVDriverOrganization;
import Business.Organization.Organization;
import Business.StationMap.Coordinate;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DriverNewLocationRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adam
 */
public class ReviewShortageRequestJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form ReviewShortageRequestJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Map<String,Coordinate> addressCodeMap;

    ReviewShortageRequestJPanel (JPanel userProcessContainer, EcoSystem system, UserAccount account, Map<String, Coordinate> addressCodeMap)
    {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.account=account;
        this.addressCodeMap=addressCodeMap;
        Object key = addressCodeMap.keySet().toArray()[0];
        txtPlace.setText((String)key);
        txtGeoCoding.setText(addressCodeMap.get(key).toString());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGeoCoding = new javax.swing.JTextField();
        txtNumCP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Review Your Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Place where shortage happened");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 250, 30));

        txtPlace.setEnabled(false);
        add(txtPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 230, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("GeoCoding of the place");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txtGeoCoding.setEnabled(false);
        add(txtGeoCoding, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 230, 30));
        add(txtNumCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 230, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("How many ChargingPile");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setText("Submit ");
        btnSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 230, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/reviewBG.png"))); // NOI18N
        jLabel5.setText(" ");
        jLabel5.setPreferredSize(new java.awt.Dimension(1150, 600));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));
    }// </editor-fold>//GEN-END:initComponents
    public  boolean digitalCorrect(String input){
            Pattern p = Pattern.compile("^[0-9]+$");
            Matcher m = p.matcher(input);
            boolean b = m.matches();
            return b;
        }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSubmitActionPerformed
    {//GEN-HEADEREND:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //input validation here
        boolean flag = digitalCorrect(txtNumCP.getText());
        if (!flag){
            JOptionPane.showMessageDialog(null, "Please Enter A Positive Integer Value!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int number = Integer.parseInt(txtNumCP.getText());
        if (number<5 || number >50){
            JOptionPane.showMessageDialog(null, "Please Enter A Number Between 5 to 50!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object key = addressCodeMap.keySet().toArray()[0];
        DriverNewLocationRequest request = new DriverNewLocationRequest();
        request.setRequestedLocation(addressCodeMap.get(key));
        request.setFullAddress(addressCodeMap.get(key).getFullAddress());
        request.setNumPiles(number);
        request.setSender(account);
        request.setRequestDate(new Date());
        request.setStatus("PENDING");
        EVDriverOrganization o = (EVDriverOrganization)findOrganization(account.getUsername(), account.getPassword(), system);
        
        o.getDriverNewLocationWorkQueue().add(request);
        JOptionPane.showMessageDialog(null, "Submit Success!", "Success", JOptionPane.INFORMATION_MESSAGE);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        Component[] componentArray = userProcessContainer.getComponents();        
        for (Component c: componentArray){
            userProcessContainer.remove(c);
        }
        UserReportAShortageJPanel panel = new UserReportAShortageJPanel(userProcessContainer, system, account);
        userProcessContainer.add("UserReportAShortageJPanel",panel);
        layout.first(userProcessContainer);
        

        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    public static Organization findOrganization(String username, String password,EcoSystem system){
        Organization organize=null;
        for (Network net : system.getNetworkList()){
            for (Enterprise e : net.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    System.out.println(o.getUserAccountDirectory().getUserAccountList());
                    if (o.getUserAccountDirectory().authenticateUser(username, password)!=null){
                        organize = o;
                    }
                }
            }
        }
        return organize;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtGeoCoding;
    private javax.swing.JTextField txtNumCP;
    private javax.swing.JTextField txtPlace;
    // End of variables declaration//GEN-END:variables
}
