/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.User;

import Business.EcoSystem;
import Business.StationMap.Coordinate;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.json.JSONObject;

/**
 *
 * @author adam
 */
public class UserReportAShortageJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form UserComplain
     */ 
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Map<String,Coordinate> addressCodeMap;
    Coordinate co;
    
    

    UserReportAShortageJPanel (JPanel userProcessContainer, EcoSystem system, UserAccount account)
    {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system; 
        this.account=account;
        addressCodeMap=new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelGeo = new javax.swing.JLabel();
        btnShowMap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelFullAddress = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(207, 218, 218));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Request New Station");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 160, 30));

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setText("Review>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Place where shortage happened:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 320, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Please use format such as \"6 distrct avenue Boston MA\"");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 440, 30));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("GeoCoding:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        labelGeo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(labelGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 370, 30));

        btnShowMap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShowMap.setText("Show On the Map");
        btnShowMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMapActionPerformed(evt);
            }
        });
        add(btnShowMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Full Address:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        labelFullAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(labelFullAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 360, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/report.png"))); // NOI18N
        jLabel3.setText(" ");
        jLabel3.setPreferredSize(new java.awt.Dimension(1150, 600));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 740, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    public  boolean patternCorrect(String input){
        Pattern p = Pattern.compile("^[a-zA-Z0-9 ]+$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String address= txtAddress.getText();
        boolean flag=patternCorrect(address);
        String [] parsed = address.split(" ");
        if (!flag){
            JOptionPane.showMessageDialog(null, "Address should follow the format", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (address.length()==0 || parsed.length==0){
            JOptionPane.showMessageDialog(null, "Address should not be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (parsed.length<2){
            JOptionPane.showMessageDialog(null, "There should be enough information to find the place", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        
        String url="https://maps.googleapis.com/maps/api/geocode/json?&address=";
        for (int i=0;i<parsed.length-1;i++){
            url+=parsed[i]+"+";
        }
        url+=parsed[parsed.length-1];
        url+="&key=AIzaSyB4LQVH_DbM4JE9gJU8nDe9rkYL6iS2qwU";
        System.out.println(url);
        try
        {
            co=geocoding(url);
            String txtCoordinate = "Latitude: "+co.getX()+" Longtitude: "+co.getY();
            labelGeo.setText(txtCoordinate);
            labelFullAddress.setText(co.getFullAddress());
            addressCodeMap.put(address, co);
        } catch (IOException ex)
        {
            JOptionPane.showMessageDialog(null, "There is no search result matched", "Error", JOptionPane.ERROR_MESSAGE);
            return;
//            Logger.getLogger(UserReportAShortageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "There is no search result matched", "Error", JOptionPane.ERROR_MESSAGE);
            return;
//            Logger.getLogger(UserReportAShortageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNextActionPerformed
    {//GEN-HEADEREND:event_btnNextActionPerformed
        // TODO add your handling code here:
        if (addressCodeMap.size()<1){
            JOptionPane.showMessageDialog(null, "You should add one location", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ReviewShortageRequestJPanel panel = new ReviewShortageRequestJPanel(userProcessContainer,system,account,addressCodeMap);
        userProcessContainer.add("ReviewShortageRequestJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnShowMapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnShowMapActionPerformed
    {//GEN-HEADEREND:event_btnShowMapActionPerformed
        // TODO add your handling code here:
        if (co==null){
            JOptionPane.showMessageDialog(null, "You should add one location", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            UserChargingMap.init();
            UserChargingMap.navi(co);
        }catch(Exception e){
            System.out.println("Clean up,please restart");
        }
        
    }//GEN-LAST:event_btnShowMapActionPerformed

//    public  void getGeocode(String targetURL) throws MalformedURLException, IOException {
//        URL yahoo = new URL(targetURL);
//        URLConnection yc = yahoo.openConnection();
//        BufferedReader in = new BufferedReader(
//                                new InputStreamReader(
//                                yc.getInputStream()));
//        String inputLine;
//
//        while ((inputLine = in.readLine()) != null) 
//            System.out.println(inputLine);
//        in.close();
//    }
    public static Coordinate geocoding(String addr) throws Exception
{
    // build a URL

    URL url = new URL(addr);
 
    // read from the URL
    Scanner scan = new Scanner(url.openStream());
    String str = new String();
    while (scan.hasNext())
        str += scan.nextLine();
    scan.close();
 
    // build a JSON object
    JSONObject obj = new JSONObject(str);
    if (! obj.getString("status").equals("OK"))
        return null;
 
    // get the first result
    JSONObject res = obj.getJSONArray("results").getJSONObject(0);
    System.out.println(res.getString("formatted_address"));
    
    JSONObject loc =
        res.getJSONObject("geometry").getJSONObject("location");
    System.out.println("lat: " + loc.getDouble("lat") +
                        ", lng: " + loc.getDouble("lng"));
    Coordinate coor = new Coordinate(loc.getDouble("lat"),loc.getDouble("lng"));
    coor.setFullAddress(res.getString("formatted_address"));
    return coor;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelFullAddress;
    private javax.swing.JLabel labelGeo;
    private javax.swing.JTextField txtAddress;
    // End of variables declaration//GEN-END:variables
}
