/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.User;

import Business.EcoSystem;
import Business.StationMap.Coordinate;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userinterface.User.UserReportAShortageJPanel.geocoding;

/**
 *
 * @author adam
 */
public class UserLocationJPanel extends javax.swing.JPanel
{
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Coordinate co;
    int scope=5;
    String fromAddress=null;
    /**
     * Creates new form userLocationJPanel
     */


    UserLocationJPanel (JPanel userProcessContainer, EcoSystem system,UserAccount account)
    {
        
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.system=system;    
       this.account=account;
    }
    
//    public void cleanup(){
//        txtAddress.setText("");
//        comboScope.setSelectedIndex(0);
//        labelNumofChargingPiles.setText("");
//        numOfChargingStation.setText("");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGetLocation = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numOfChargingStation = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNumofChargingPiles = new javax.swing.JLabel();
        comboScope = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Your Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Please enter your location:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnGetLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGetLocation.setText("Browse");
        btnGetLocation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGetLocationActionPerformed(evt);
            }
        });
        add(btnGetLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("See all the charging station:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 197, 20));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 130, 30));

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setText("Next>");
        btnNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 120, 30));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, 30));

        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setText("Search");
        btnConfirm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Charging Station near you:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 237, -1, 30));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 176, -1, -1));

        numOfChargingStation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(numOfChargingStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Available Charging Piles near you:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        labelNumofChargingPiles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(labelNumofChargingPiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 230, 30));

        comboScope.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20" }));
        comboScope.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboScopeActionPerformed(evt);
            }
        });
        add(comboScope, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Select Your Scope:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("miles");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Please use format such as \"6 distrct avenue Boston MA\"");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 440, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/evDriverBG.png"))); // NOI18N
        jLabel10.setText(" ");
        jLabel10.setPreferredSize(new java.awt.Dimension(1150, 600));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1250, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetLocationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetLocationActionPerformed
    {//GEN-HEADEREND:event_btnGetLocationActionPerformed
        // TODO add your handling code here:
        try{
            UserChargingMap.init();
            UserChargingMap.navi(system);
        }catch(Exception e){
            System.out.println("Clean up, please restart");
        }
        
    }//GEN-LAST:event_btnGetLocationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNextActionPerformed
    {//GEN-HEADEREND:event_btnNextActionPerformed
        // TODO add your handling code here:
//        double latitude  = Double.valueOf(txtLatitude.getText());
//        double longtitude  = Double.valueOf(txtLongtitude.getText());
//        Coordinate coordinate= new Coordinate(latitude,longtitude);
        
        if (co==null){
            JOptionPane.showMessageDialog(null, "Please select your address first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        account.setCoordinate(co);
        UserChooseChargingStationJPanel panel = new UserChooseChargingStationJPanel(userProcessContainer,system,account);
        userProcessContainer.add("UserFindChargingStation", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtAddressActionPerformed
    {//GEN-HEADEREND:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed
    public  boolean patternCorrect(String input){
        Pattern p = Pattern.compile("^[a-zA-Z0-9 ]+$");
        Matcher m = p.matcher(input);
        boolean b = m.matches();
        return b;
    }
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmActionPerformed
    {//GEN-HEADEREND:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String address = txtAddress.getText();
        boolean flag=patternCorrect(address);
        String [] parsed = address.split(" ");
        if (!flag){
            JOptionPane.showMessageDialog(null, "Address should follow the format", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (address.length()==0 || parsed.length==0){
            JOptionPane.showMessageDialog(null, "Address should not be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (parsed.length<2){
            JOptionPane.showMessageDialog(null, "There should be enough information to find the place", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        
        String url="https://maps.googleapis.com/maps/api/geocode/json?&address=";
        for (int i=0;i<parsed.length-1;i++){
            url+=parsed[i]+"+";
        }
        url+=parsed[parsed.length-1];
        url+="&key=AIzaSyB4LQVH_DbM4JE9gJU8nDe9rkYL6iS2qwU";
        System.out.println(url);
        try
        {
            co=geocoding(url);
            String txtCoordinate = "Latitude: "+co.getX()+" Longtitude: "+co.getY();
            numOfChargingStation.setText(String.valueOf(system.getStationmap().findNumOfChargingStation(scope, co)));
            labelNumofChargingPiles.setText(String.valueOf(system.getStationmap().findNumOfChargingPiles(scope, co)));
            
        } catch (IOException ex)
        {
            JOptionPane.showMessageDialog(null, "There is no search result matched", "Error", JOptionPane.ERROR_MESSAGE);
            return;
//            Logger.getLogger(UserReportAShortageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "There is no search result matched", "Error", JOptionPane.ERROR_MESSAGE);
            return;
//            Logger.getLogger(UserReportAShortageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void comboScopeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboScopeActionPerformed
    {//GEN-HEADEREND:event_comboScopeActionPerformed
        // TODO add your handling code here:
        if (co==null){
            comboScope.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Please enter Your location First", "Select", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        scope =Integer.parseInt((String)comboScope.getSelectedItem());
        numOfChargingStation.setText(String.valueOf(system.getStationmap().findNumOfChargingStation(scope, co)));
        labelNumofChargingPiles.setText(String.valueOf(system.getStationmap().findNumOfChargingPiles(scope, co)));
        
    }//GEN-LAST:event_comboScopeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnGetLocation;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> comboScope;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelNumofChargingPiles;
    private javax.swing.JLabel numOfChargingStation;
    private javax.swing.JTextField txtAddress;
    // End of variables declaration//GEN-END:variables
}
